### PR TITLE
Just checking pull request

### PR DESCRIPTION
**Pull request by Northernn**
Changes to warmap for teleport in NF
Basic supply line check

### CODE REVIEW

**Comment by Northernn** [comment]
The teleport button doesn't work at all if you leave the 1115 bit in there, if you remove it it works fine. 
So it depends on what you mean by fully implemented it, if you mean to be live like then no it isn't, but if you mean to be able to teleport then the code is already there just this version check stops it from working. 
DOL removed it too I found out afterwards for the same reason. I don't see why it would effect the OF anyway as it is only triggered when they press the teleport button on the warmap in the game.

**Comment by Northernn** [comment]
https://github.com/Dawn-of-Light/DOLSharp/commit/ad0e5952902f4548935f45d3f81ca86586403d99

**Comment by bm01** [comment]
> So it depends on what you mean by fully implemented it

I was refering to this comment https://github.com/OpenDAoC/OpenDAoC-Core/pull/45/commits/afcd34a53d76d3af063aeebe7dbf80e57fc828ae#diff-bd264039b9d67002f09c08b893129f0554b1c5a1ed96a3dca7f002bd3a11e441R138
Could you make the supply chain propagate to other regions? I could merge as is but it would be nice to have it working.

Also a random idea, I noticed plvl 2 and 3 characters are allowed to teleport from any region, but trying to do so by selecting a keep on the OF warmap tries to teleport the player to a non existent zone in region 163, because it only picks up the keep's coordinates, not its region. By using its region, I think we could make it work on OF too for GMs / admins.

**Comment by Northernn** [comment]
actually it should probably do a config check too first for use_supply_chain option, some might not want it.
Will look at this and the region fix.

**Comment by Northernn** [comment]
From what I remember old frontiers do not use the warmap or portal stones, are you thinking from a blackthorn point of view rather than a Live-like point of view?   From what I remember the maps in the warmap would need to be changed to support the warmap and teleport? So to keep this right wouldn't it need to only be the 163 zone anyway?

**Comment by bm01** [comment]
The warmap is indeed supposed to be a NF thing, but since we're all using newer clients, it's still possible to open the window. By default, OF keeps aren't placed correctly (here's an old screenshot from Uthgard: https://i.imgur.com/ytpyXeC.jpeg), but at some point someone from Atlas (forgot who) tried to make it work. And I thought it was pretty much done, but looking at it more closely many are still misplaced:
image
image
image

We don't technically need to check for NF because players still need to be next to a teleportation stone anyway, and it would be nice to allow server owners to add teleport stones and have a functional teleport system in OF, or even have it working for GMs / Admins. Then the supply chain mechanic would probably have to be different so ideally it should be easily configurable via DB entries...

But that's way out of the scope of this issue since it requires client modifications, and I don't even know if it's possible to make every OF keep have their correct position on the warmap.

So yeah, we can forget that for now. But regardless, I think it's good practice to remove direct references to internal IDs whenever possible, for various reasons. Ideally even methods such as `Zone.IsOF` shouldn't check internal IDs, and OF zones / region should be marked as such in the DB instead. But the main thing I want to prevent is `GamePlayer.MoveTo` being called with arguments that don't match a valid game location, which currently can happen for GMs / Admins.

**Comment by Northernn** [comment]
Ah ok not seen that before. 
I have changed it so you can turn off supply line check and it uses .IsFrontier now instead of = 168 so you just need to flag the region as a frontier in the database. I don't have the OF patch so it shows all of the NF maps. do you have a client, maybe blackthorn? that uses the OF maps so I can get that working.

**Comment by bm01** [comment]
`Region.IsFrontier` can't be used for servers using OF since the zones are in the main regions. This property is currently unused in OpenDAoC for this reason. In fact we should move that column to the zone table.

**Comment by bm01** [comment]
Closing due to inactivity. But feel free to reopen with a branch that includes your latest changes.

**Pull request closed without merging**
